server:
  port: 8000

spring:
  application:
    name: sunshine-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 8.140.48.6:8848
        username: nacos
        password: nacos
      config:
        server-addr: 8.140.48.6:8848
        username: nacos
        password: nacos
        import-check:
          enabled: false
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  sentinel:
    transport:
      dashboard: 8.140.48.6:8858

logging:
  level:
    com.sunshine: debug
