server:
  port: 8000

spring:
  main:
    web-application-type: reactive
  application:
    name: sunshine-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ecs4c16g:8848
        username: nacos
        password: nacos
      config:
        server-addr: ecs4c16g:8848
        username: nacos
        password: nacos
        import-check:
          enabled: false
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: sunshine-bff-api
          uri: lb://sunshine-bff
          predicates:
            - Path=/api/**
        - id: sunshine-llm-gateway-api
          uri: lb://sunshine-llm-gateway
          predicates:
            - Path=/v1/**
  sentinel:
    transport:
      dashboard: ecs4c16g:8858

logging:
  level:
    com.sunshine: debug
