server:
  port: 8700

spring:
  application:
    name: sunshine-oa
  cloud:
    nacos:
      discovery:
        server-addr: ecs4c16g:8848
        username: nacos
        password: nacos
        group: SUNSHINE_V2
        metadata:
          sunshine.tool-app: "true"
          sunshine.tool-app-id: "sunshine-oa"

sunshine:
  tools:
    enabled: true
    app-id: sunshine-oa

logging:
  level:
    com.sunshine: debug
