server:
  port: 8700

spring:
  application:
    name: sunshine-oa
  cloud:
    nacos:
      discovery:
        server-addr: ecs4c16g:8848
        username: nacos
        password: nacos

logging:
  level:
    com.sunshine: debug
