-- sunshine-workflow-manager（workflow-manager :8230 · 库 sunshine_workflow · 全量 v1）
USE sunshine_workflow;

CREATE TABLE workflow_definition (
    tenant_id       VARCHAR(64) NOT NULL DEFAULT 'default',
    id              VARCHAR(64) NOT NULL,
    display_name    VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    mode            VARCHAR(24) NOT NULL DEFAULT 'workflow',
    enabled         TINYINT(1) NOT NULL DEFAULT 0,
    active_version  INT NOT NULL DEFAULT 0,
    source          VARCHAR(16) NOT NULL DEFAULT 'studio',
    kind            VARCHAR(16) NOT NULL DEFAULT 'all' COMMENT '会话形态：chat|task|all（与 conversation.kind 同轴）',
    maintainer      VARCHAR(64),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id)
);

CREATE TABLE workflow_version (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id       VARCHAR(64) NOT NULL,
    workflow_id     VARCHAR(64) NOT NULL,
    version         INT NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'draft',
    plan_json       MEDIUMTEXT NOT NULL,
    catalog_meta    JSON,
    published_at    TIMESTAMP NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_workflow_version (tenant_id, workflow_id, version),
    CONSTRAINT fk_workflow_version_def FOREIGN KEY (tenant_id, workflow_id)
        REFERENCES workflow_definition (tenant_id, id)
);

-- 标杆 workflow 种子（published v1，plan_json 含 layout；source=seed；节点 id = {type}-{8位hex}；由 scripts/sync_enterprise_workflows.py --write-sql 生成）

-- finance-list
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'finance-list', '我的报销查询', '列出当前用户报销单（可按 status），不做合规分析', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'finance-list', 1, 'published', '{"planId":null,"reason":"导入自 sunshine-workflows.yaml · finance-list","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"tool-f7a3b2c1","type":"tool","displayName":"查询我的报销单","params":{"tool":"sdk__sunshine-biz__list_my_expenses","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"},"inputs":[{"name":"status","source":"{{plan.params.status}}","type":"string","required":false}]},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据财务工具查询结果回答用户问题。\\n\\n约束：\\n- 仅依据下方「数据」作答；数据中未出现的制度条文、审批标准、金额门槛等一律禁止撰写或猜测。\\n- 本流程只查询我的报销单：即使用户提到「循环 / 检索制度 / 合规分析」，也只列示数据中的单据；可用一句话说明「当前流程仅列出我的报销」。\\n- 禁止向用户暴露英文流程/工具内部名。\\n- 若「数据」中非空（有条目、条数>0、含 id/金额/标题等），必须逐条列出，不得回答「没有数据」。\\n- 仅当数据明确为空数组或条数为 0 时，才可说明当前无报销记录。\\n- 不要编造单据；不要省略工具返回的字段。\\n- 输出用简洁 Markdown 列表或表格列单据即可，勿写长篇合规/制度报告。\\n\\n数据：\\n{{tool-f7a3b2c1.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"tool-f7a3b2c1"},{"from":"tool-f7a3b2c1","to":"answer"}],"layout":{"start":{"x":48,"y":72},"tool-f7a3b2c1":{"x":268,"y":72},"answer":{"x":488,"y":72}}}', '{"examples":["我有哪些待报销","列出我的报销单"],"nodeSummary":["start","tool","answer"]}', CURRENT_TIMESTAMP);

-- finance-smart
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'finance-smart', '报销智能分析', '对照费用制度只读分析当前用户报销是否合规（含 Agent；不可提交报销）', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'finance-smart', 1, 'published', '{"planId":null,"reason":"企业化只读报销分析：rag→list→agent(finance-analysis，无 submit)","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"rag-fsmart1","type":"rag","displayName":"费用制度检索","params":{"query":"费用差旅网约车报销：{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"tool-d4e8f901","type":"tool","displayName":"查询我的报销单","params":{"tool":"sdk__sunshine-biz__list_my_expenses","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"},"inputs":[{"name":"status","source":"{{plan.params.status}}","type":"string","required":false}]},{"id":"agent-b2c6d803","type":"agent","displayName":"智能体分析","params":{"query":"{{start.userQuery}}","context":"制度检索：{{rag-fsmart1.output}}\\n报销列表：{{tool-d4e8f901.output}}","skill":"finance-analysis","tools":"sdk__sunshine-biz__list_my_expenses,sdk__sunshine-biz__get_expense_detail","maxIters":"4","systemOverlay":"本节点仅输出内部只读分析结论，不面向用户；禁止调用白名单外工具；禁止提交报销；禁止虚构金额。","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据 Agent 分析结果生成用户可见回答。\\n\\n约束：禁止向用户暴露英文流程/工具内部名；仅依据下方分析作答。\\n\\n分析：\\n{{agent-b2c6d803.answer}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"rag-fsmart1"},{"from":"rag-fsmart1","to":"tool-d4e8f901"},{"from":"tool-d4e8f901","to":"agent-b2c6d803"},{"from":"agent-b2c6d803","to":"answer"}],"layout":{"start":{"x":48,"y":72},"rag-fsmart1":{"x":248,"y":72},"tool-d4e8f901":{"x":448,"y":72},"agent-b2c6d803":{"x":648,"y":72},"answer":{"x":868,"y":72}}}', '{"examples":["对照制度看我的报销是否合规","分析我的报销与费用制度"],"nodeSummary":["start","rag","tool","agent","answer"]}', CURRENT_TIMESTAMP);

-- finance-summary
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'finance-summary', '报销汇总统计', '按状态汇总当前用户报销单条数与金额', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'finance-summary', 1, 'published', '{"planId":null,"reason":"导入自 sunshine-workflows.yaml · finance-summary","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"tool-a9c1e502","type":"tool","displayName":"汇总我的报销","params":{"tool":"sdk__sunshine-biz__summarize_my_expenses","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"},"inputs":[{"name":"status","source":"{{plan.params.status}}","type":"string","required":false}]},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据财务汇总工具结果回答用户。\\n\\n约束：禁止向用户暴露英文流程/工具内部名。\\n\\n汇总：\\n{{tool-a9c1e502.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"tool-a9c1e502"},{"from":"tool-a9c1e502","to":"answer"}],"layout":{"start":{"x":48,"y":72},"tool-a9c1e502":{"x":268,"y":72},"answer":{"x":488,"y":72}}}', '{"examples":["我的报销汇总有多少","按状态统计我的报销金额"],"nodeSummary":["start","tool","answer"]}', CURRENT_TIMESTAMP);

-- knowledge-qa
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'knowledge-qa', '知识库问答', '查企业制度/流程/规定（青松假、网约车上限、安全/IT/法务/行政/PMO 等）；非查个人单据列表或合规对比', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'knowledge-qa', 1, 'published', '{"planId":null,"reason":"导入自 sunshine-workflows.yaml · knowledge-qa","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"rag-c5d7e903","type":"rag","displayName":"知识检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"你是企业制度问答助手。仅根据下方「检索结果」回答，不得编造公司制度。\\n\\n若「检索结果」正文为空、或明确写「未找到与用户问题直接相关的片段」，只回复：\\n「企业知识库中暂无相关规定，请咨询 HR/财务或相关主管部门。」\\n若检索结果非空且含与用户问题相关的制度片段（表述可不完全一致，如打车/差旅/交通费/报销），须基于片段作答，不得回复暂无。\\n禁止用通用常识、网络知识或税务/法律科普代替企业制度。\\n禁止向用户输出 finance-list、finance-smart、knowledge-qa 等内部名称；改用中文业务表述。\\n\\n检索结果：\\n{{rag-c5d7e903.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"rag-c5d7e903"},{"from":"rag-c5d7e903","to":"answer"}],"layout":{"start":{"x":48,"y":72},"rag-c5d7e903":{"x":268,"y":72},"answer":{"x":488,"y":72}}}', '{"examples":["青松假有多少天、怎么申请","市内网约车报销上限多少","锁钥通道申请流程是什么"],"nodeSummary":["start","rag","answer"]}', CURRENT_TIMESTAMP);

-- knowledge-dual
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'knowledge-dual', '双路知识检索', '人事与费用制度并行检索后汇总（如青松假+网约车上限；4.7.2 join 标杆）', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'knowledge-dual', 1, 'published', '{"planId":null,"reason":"4.7.2 并行双 RAG 标杆（BPMN parallel-gateway）","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"pg-a1b2c3d4","type":"parallel-gateway","displayName":"并行分叉","params":{"retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"rag-a1b2c3d4","type":"rag","displayName":"人事制度检索","params":{"query":"人事制度：{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"rag-e5f6a7b8","type":"rag","displayName":"费用制度检索","params":{"query":"费用制度：{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"join-c9d0e1f2","type":"join","displayName":"并行汇总","params":{"retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"你是企业知识助手。综合下方「人事制度检索」与「费用制度检索」结果回答，不得编造。\\n\\n若两路均为空，回复：企业知识库中暂无相关规定。\\n禁止暴露英文流程/工具内部名。\\n\\n人事制度检索：\\n{{rag-a1b2c3d4.output}}\\n\\n费用制度检索：\\n{{rag-e5f6a7b8.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"pg-a1b2c3d4"},{"from":"pg-a1b2c3d4","to":"rag-a1b2c3d4"},{"from":"pg-a1b2c3d4","to":"rag-e5f6a7b8"},{"from":"rag-a1b2c3d4","to":"join-c9d0e1f2"},{"from":"rag-e5f6a7b8","to":"join-c9d0e1f2"},{"from":"join-c9d0e1f2","to":"answer"}],"layout":{"start":{"x":48,"y":72},"pg-a1b2c3d4":{"x":322,"y":80},"rag-a1b2c3d4":{"x":488,"y":28},"rag-e5f6a7b8":{"x":488,"y":116},"join-c9d0e1f2":{"x":762,"y":80},"answer":{"x":928,"y":72}}}', '{"examples":["青松假和网约车报销上限一起查","青松假有多少天、怎么申请"],"nodeSummary":["start","parallel-gateway","rag","join","answer"]}', CURRENT_TIMESTAMP);

-- knowledge-branch
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'knowledge-branch', '条件分支知识检索', '含「报销」或「发票」走财务 RAG，否则走人事 RAG（4.13.7 exclusive-gateway OR 多条件标杆）', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'knowledge-branch', 1, 'published', '{"planId":null,"reason":"4.13.7 exclusive-gateway OR 多条件边条件标杆（报销 OR 发票）","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"xg-b1c2d3e4","type":"exclusive-gateway","displayName":"条件分支","params":{"retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"rag-f1a2b3c4","type":"rag","displayName":"财务制度检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"rag-d5e6f7a8","type":"rag","displayName":"人事制度检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"你是企业制度助手。根据下方检索结果回答，不得编造。\\n\\n若检索为空，回复：企业知识库中暂无相关规定。\\n禁止暴露 knowledge-branch 等内部名称。\\n\\n财务制度检索：\\n{{rag-f1a2b3c4.output}}\\n\\n人事制度检索：\\n{{rag-d5e6f7a8.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"xg-b1c2d3e4"},{"from":"xg-b1c2d3e4","to":"rag-f1a2b3c4","condition":{"logic":"or","items":[{"left":"{{start.userQuery}}","op":"contains","right":"报销"},{"left":"{{start.userQuery}}","op":"contains","right":"发票"}]}},{"from":"xg-b1c2d3e4","to":"rag-d5e6f7a8","default":true},{"from":"rag-f1a2b3c4","to":"answer"},{"from":"rag-d5e6f7a8","to":"answer"}],"layout":{"start":{"x":48,"y":72},"xg-b1c2d3e4":{"x":280,"y":80},"rag-f1a2b3c4":{"x":480,"y":28},"rag-d5e6f7a8":{"x":480,"y":116},"answer":{"x":720,"y":72}}}', '{"examples":["网约车报销需要哪些材料","青松假怎么申请"],"nodeSummary":["start","exclusive-gateway","rag","answer"],"intentAfter":"将按条件分支知识检索流程处理"}', CURRENT_TIMESTAMP);

-- knowledge-loop
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'knowledge-loop', '条件循环知识检索', 'do-while：首轮必进框内 rag→报销列表→假期余额→agent；检索含「继续」且待报销未「已完成」则再轮（AND 多条件，最多 2，超限 exit）（4.13.7）', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'knowledge-loop', 1, 'published', '{"planId":null,"reason":"4.13.7 loop 容器标杆（do-while 多条件 AND：检索含「继续」且待报销未「已完成」则再轮；框内 rag→list→leave→agent）","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"loop-a1b2c3d4","type":"loop","displayName":"条件循环","params":{"conditions":[{"left":"{{rag-l1o2o3p4.output}}","op":"contains","right":"继续"},{"left":"{{tool-t1o2o3p4.output}}","op":"not_contains","right":"已完成"}],"conditionLogic":"and","maxIterations":"2","onMaxIterations":"exit","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"fail_fast"}},{"id":"rag-l1o2o3p4","type":"rag","parentId":"loop-a1b2c3d4","displayName":"知识检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"tool-t1o2o3p4","type":"tool","parentId":"loop-a1b2c3d4","displayName":"查询我的待报销","params":{"tool":"sdk__sunshine-biz__list_my_expenses","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"},"inputs":[{"name":"status","source":"{{plan.params.status}}","type":"string","required":false}]},{"id":"tool-leave01","type":"tool","parentId":"loop-a1b2c3d4","displayName":"查询假期余额","params":{"tool":"sdk__sunshine-biz__get_leave_balance","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"agent-a1g2e3n4","type":"agent","parentId":"loop-a1b2c3d4","displayName":"综合分析","params":{"query":"{{start.userQuery}}","context":"检索：{{rag-l1o2o3p4.output}}\\n待报销：{{tool-t1o2o3p4.output}}\\n假期余额：{{tool-leave01.output}}","skill":"finance-analysis","tools":"sdk__sunshine-biz__list_my_expenses","maxIters":"3","systemOverlay":"本节点仅输出内部分析结论；综合制度检索、待报销与假期余额，禁止编造。","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"你是企业助手。根据下方循环分析结论回答，不得编造。\\n\\n若结论为空，回复：暂无可用结果。\\n禁止暴露 knowledge-loop 等内部名称。\\n\\n循环分析：\\n{{loop-a1b2c3d4.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"loop-a1b2c3d4"},{"from":"rag-l1o2o3p4","to":"tool-t1o2o3p4"},{"from":"tool-t1o2o3p4","to":"tool-leave01"},{"from":"tool-leave01","to":"agent-a1g2e3n4"},{"from":"loop-a1b2c3d4","to":"answer"}],"layout":{"start":{"x":48,"y":72},"loop-a1b2c3d4":{"x":200,"y":40,"width":780,"height":160},"rag-l1o2o3p4":{"x":224,"y":92},"tool-t1o2o3p4":{"x":400,"y":92},"tool-leave01":{"x":576,"y":92},"agent-a1g2e3n4":{"x":752,"y":92},"answer":{"x":1040,"y":72}}}', '{"examples":["分析青松假余额和我的待报销","继续分析青松假余额和我的待报销"],"nodeSummary":["start","loop","rag","tool","agent","answer"],"intentAfter":"将按条件循环（检索→工具→智能体）流程处理"}', CURRENT_TIMESTAMP);

-- sandbox-agent
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'sandbox-agent', '工作区沙箱写文件', 'Workflow agent 节点默认沙箱：用沙箱工具在对话工作区写文件后汇总（4.5 SUB 默认沙箱标杆）', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'sandbox-agent', 1, 'published', '{"planId":null,"reason":"4.5 SUB 默认沙箱标杆（start→agent→answer；复用对话级 /workspace）","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"agent-s4b0x7a1","type":"agent","displayName":"沙箱写文件","params":{"query":"{{start.userQuery}}","context":"请在对话沙箱 /workspace 完成用户请求的文件写入；沙箱六工具已注入，无需 Catalog 白名单。","maxIters":"4","systemOverlay":"本节点为 Workflow 子 Agent，仅输出内部结论供下游润色。\\n必须使用 sandbox__write（新建）或 sandbox__edit（已存在）在 /workspace 落盘；过渡语后立刻 tool call。\\n禁止编造「已写入」而未实际调用工具；完成后用简短中文说明路径与要点。","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据子 Agent 结论生成用户可见回答。\\n\\n约束：禁止暴露 sandbox-agent、sandbox__* 等内部名；用中文说明已写入的工作区文件路径与内容要点。\\n\\n子 Agent 结论：\\n{{agent-s4b0x7a1.answer}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"agent-s4b0x7a1"},{"from":"agent-s4b0x7a1","to":"answer"}],"layout":{"start":{"x":48,"y":72},"agent-s4b0x7a1":{"x":268,"y":72},"answer":{"x":488,"y":72}}}', '{"examples":["在工作区写一份 hello.txt 内容为 hello sandbox","用沙箱新建 /workspace/note.md"],"nodeSummary":["start","agent","answer"],"intentAfter":"将按工作区沙箱写文件流程处理"}', CURRENT_TIMESTAMP);

-- hr-leave-assist
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'hr-leave-assist', '假期助手', '检索假期制度并查询余额/请假单；用户明确申请时可 submit（HITL）', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'hr-leave-assist', 1, 'published', '{"planId":null,"reason":"企业假期助手：rag→余额→请假列表→agent(可 submit_leave)","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"rag-hrleave1","type":"rag","displayName":"假期制度检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"tool-hrbal01","type":"tool","displayName":"查询假期余额","params":{"tool":"sdk__sunshine-biz__get_leave_balance","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"tool-hrlist01","type":"tool","displayName":"查询请假单","params":{"tool":"sdk__sunshine-biz__list_leave_requests","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"agent-hrleave1","type":"agent","displayName":"假期助手","params":{"query":"{{start.userQuery}}","context":"制度：{{rag-hrleave1.output}}\\n余额：{{tool-hrbal01.output}}\\n请假单：{{tool-hrlist01.output}}","skill":"policy-review","tools":"sdk__sunshine-biz__submit_leave_request","maxIters":"4","systemOverlay":"仅当用户明确申请且假别/日期等参数齐全时调用提交请假；否则只输出只读结论；禁止编造余额或单据。","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据上游检索、工具与 Agent 结论回答用户。\\n\\n约束：禁止向用户暴露英文流程/工具内部名；仅依据下方数据与结论作答，禁止编造。\\n\\n制度：\\n{{rag-hrleave1.output}}\\n\\n余额：\\n{{tool-hrbal01.output}}\\n\\n请假单：\\n{{tool-hrlist01.output}}\\n\\nAgent 结论：\\n{{agent-hrleave1.answer}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"rag-hrleave1"},{"from":"rag-hrleave1","to":"tool-hrbal01"},{"from":"tool-hrbal01","to":"tool-hrlist01"},{"from":"tool-hrlist01","to":"agent-hrleave1"},{"from":"agent-hrleave1","to":"answer"}],"layout":{"start":{"x":48,"y":72},"rag-hrleave1":{"x":248,"y":72},"tool-hrbal01":{"x":448,"y":72},"tool-hrlist01":{"x":648,"y":72},"agent-hrleave1":{"x":848,"y":72},"answer":{"x":1068,"y":72}}}', '{"examples":["青松假还有几天，我的请假单呢","帮我申请明天一天青松假"],"nodeSummary":["start","rag","tool","agent","answer"],"intentAfter":"将按假期助手流程处理"}', CURRENT_TIMESTAMP);

-- expense-compliance
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'expense-compliance', '费用合规闭环', '检索费用制度并列出我的报销；合规分析，明确提交时可 submit_expense（HITL）', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'expense-compliance', 1, 'published', '{"planId":null,"reason":"费用合规闭环：rag→list→agent(可 submit_expense)","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"rag-expcomp1","type":"rag","displayName":"费用制度检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"tool-explist1","type":"tool","displayName":"查询我的报销单","params":{"tool":"sdk__sunshine-biz__list_my_expenses","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"},"inputs":[{"name":"status","source":"{{plan.params.status}}","type":"string","required":false}]},{"id":"agent-expcomp1","type":"agent","displayName":"合规分析","params":{"query":"{{start.userQuery}}","context":"制度：{{rag-expcomp1.output}}\\n报销列表：{{tool-explist1.output}}","skill":"compliance-check","tools":"sdk__sunshine-biz__list_my_expenses,sdk__sunshine-biz__get_expense_detail,sdk__sunshine-biz__submit_expense","maxIters":"4","systemOverlay":"仅当用户明确要求提交且金额/事由等参数齐全时调用提交报销；否则只输出合规只读结论；禁止虚构金额与单据。","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据上游检索、工具与 Agent 结论回答用户。\\n\\n约束：禁止向用户暴露英文流程/工具内部名；仅依据下方数据与结论作答，禁止编造。\\n\\n制度：\\n{{rag-expcomp1.output}}\\n\\n报销列表：\\n{{tool-explist1.output}}\\n\\nAgent 结论：\\n{{agent-expcomp1.answer}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"rag-expcomp1"},{"from":"rag-expcomp1","to":"tool-explist1"},{"from":"tool-explist1","to":"agent-expcomp1"},{"from":"agent-expcomp1","to":"answer"}],"layout":{"start":{"x":48,"y":72},"rag-expcomp1":{"x":248,"y":72},"tool-explist1":{"x":468,"y":72},"agent-expcomp1":{"x":688,"y":72},"answer":{"x":908,"y":72}}}', '{"examples":["网约车上限对照我的报销，必要时帮我提交一笔","对照制度看我的报销是否合规"],"nodeSummary":["start","rag","tool","agent","answer"],"intentAfter":"将按费用合规闭环流程处理"}', CURRENT_TIMESTAMP);

-- oa-task-assist
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'oa-task-assist', 'OA 待办助手', '列出我的 OA 待办；用户点名 taskId 时可审批（HITL）', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'oa-task-assist', 1, 'published', '{"planId":null,"reason":"OA 待办助手：list→agent(可 approve)","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"tool-oalist01","type":"tool","displayName":"查询 OA 待办","params":{"tool":"sdk__sunshine-biz__list_oa_tasks","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"agent-oaassist1","type":"agent","displayName":"OA 助手","params":{"query":"{{start.userQuery}}","context":"待办列表：{{tool-oalist01.output}}","tools":"sdk__sunshine-biz__approve_oa_task","maxIters":"3","systemOverlay":"仅审批用户明确点名的 taskId；否则只列示/说明待办；禁止编造 taskId。","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据上游工具与 Agent 结论回答用户。\\n\\n约束：禁止向用户暴露英文流程/工具内部名；仅依据下方数据与结论作答，禁止编造。\\n\\n待办列表：\\n{{tool-oalist01.output}}\\n\\nAgent 结论：\\n{{agent-oaassist1.answer}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"tool-oalist01"},{"from":"tool-oalist01","to":"agent-oaassist1"},{"from":"agent-oaassist1","to":"answer"}],"layout":{"start":{"x":48,"y":72},"tool-oalist01":{"x":268,"y":72},"agent-oaassist1":{"x":488,"y":72},"answer":{"x":708,"y":72}}}', '{"examples":["我的 OA 待办有哪些","批准 taskId 为 xxx 的待办"],"nodeSummary":["start","tool","agent","answer"],"intentAfter":"将按 OA 待办助手流程处理"}', CURRENT_TIMESTAMP);

-- expense-detail-query
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'expense-detail-query', '报销单详情查询', 'parameter-extractor 提取报销单 ID → 查询详情 → 展示（结构化 IO 标杆）', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'expense-detail-query', 1, 'published', '{"planId":null,"reason":"结构化 IO 标杆：parameter-extractor 提取 expenseId → get_expense_detail 详情","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"pe-extract01","type":"parameter-extractor","displayName":"参数提取","params":{"input":"{{start.userQuery}}","instruction":"从用户问题中提取报销单 ID（expenseId）。如果用户提到多个，取第一个。","schema":"{\\"expenseId\\": {\\"type\\": \\"string\\", \\"description\\": \\"报销单 ID，如 EXP-2024-001\\"}}","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"fail_fast"}},{"id":"tool-detail01","type":"tool","displayName":"查询报销详情","params":{"tool":"sdk__sunshine-biz__get_expense_detail","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"},"inputs":[{"name":"expenseId","source":"{{pe-extract01.expenseId}}","type":"string","required":true}]},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据报销单详情回答用户。\\n\\n约束：禁止暴露英文流程/工具内部名；仅依据下方数据作答。\\n\\n报销单详情：\\n{{tool-detail01.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"pe-extract01"},{"from":"pe-extract01","to":"tool-detail01"},{"from":"tool-detail01","to":"answer"}],"layout":{"start":{"x":48,"y":72},"pe-extract01":{"x":248,"y":72},"tool-detail01":{"x":468,"y":72},"answer":{"x":688,"y":72}}}', '{"examples":["查询 EXP-2024-001 的报销详情","帮我看看报销单 EXP-2024-001 的明细"],"nodeSummary":["start","parameter-extractor","tool","answer"],"intentAfter":"将按报销单详情查询流程处理"}', CURRENT_TIMESTAMP);

-- expense-status-filter
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'expense-status-filter', '报销状态筛选查询', 'variable-assignment 定义查询条件 → 按状态筛选报销单（字面量 inputs 标杆）', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'expense-status-filter', 1, 'published', '{"planId":null,"reason":"结构化 IO 标杆：variable-assignment 定义 status 变量 → tool 字面量绑定","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"va-setstatus","type":"variable-assignment","displayName":"设置查询条件","params":{"assignments":"[{\\"name\\": \\"targetStatus\\", \\"source\\": \\"pending\\", \\"type\\": \\"string\\"}, {\\"name\\": \\"queryDesc\\", \\"source\\": \\"{{start.userQuery}}\\", \\"type\\": \\"string\\"}]","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"fail_fast"}},{"id":"tool-filter01","type":"tool","displayName":"按状态查询报销","params":{"tool":"sdk__sunshine-biz__list_my_expenses","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"},"inputs":[{"name":"status","source":"{{va-setstatus.targetStatus}}","type":"string","required":false}]},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据筛选结果回答用户。\\n\\n约束：禁止暴露英文流程/工具内部名；仅依据下方数据作答。\\n\\n查询条件：{{va-setstatus.targetStatus}}\\n筛选结果：\\n{{tool-filter01.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"va-setstatus"},{"from":"va-setstatus","to":"tool-filter01"},{"from":"tool-filter01","to":"answer"}],"layout":{"start":{"x":48,"y":72},"va-setstatus":{"x":248,"y":72},"tool-filter01":{"x":468,"y":72},"answer":{"x":688,"y":72}}}', '{"examples":["查询我所有待审批的报销单","列出 pending 状态的报销"],"nodeSummary":["start","variable-assignment","tool","answer"],"intentAfter":"将按报销状态筛选查询流程处理"}', CURRENT_TIMESTAMP);

-- expense-amount-check
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source, kind) VALUES ('default', 'expense-amount-check', '报销金额合规检查', '查询报销汇总 → 提取总金额 → 合规判断（嵌套路径引用标杆）', 'workflow', 1, 1, 'seed', 'chat');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'expense-amount-check', 1, 'published', '{"planId":null,"reason":"结构化 IO 标杆：tool output 嵌套字段（totalAmount）→ agent 合规分析","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"tool-sumcheck","type":"tool","displayName":"汇总报销金额","params":{"tool":"sdk__sunshine-biz__summarize_my_expenses","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"},"inputs":[{"name":"status","source":"approved","type":"string","required":false}]},{"id":"agent-amount01","type":"agent","displayName":"金额合规分析","params":{"query":"{{start.userQuery}}","context":"报销汇总数据：{{tool-sumcheck.output}}\\n已批准报销总金额：{{tool-sumcheck.output.totalAmount}} 元\\n报销单数量：{{tool-sumcheck.output.count}} 笔","skill":"compliance-check","maxIters":"3","systemOverlay":"仅基于上游汇总数据做金额合规分析；禁止编造金额；如总金额超过 10000 元需提示超标风险。","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据金额合规分析结果回答用户。\\n\\n约束：禁止暴露英文流程/工具内部名；仅依据下方分析作答。\\n\\n合规分析：\\n{{agent-amount01.answer}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"tool-sumcheck"},{"from":"tool-sumcheck","to":"agent-amount01"},{"from":"agent-amount01","to":"answer"}],"layout":{"start":{"x":48,"y":72},"tool-sumcheck":{"x":268,"y":72},"agent-amount01":{"x":488,"y":72},"answer":{"x":708,"y":72}}}', '{"examples":["我的已批准报销总金额是否超标","检查我的报销金额合规性"],"nodeSummary":["start","tool","agent","answer"],"intentAfter":"将按报销金额合规检查流程处理"}', CURRENT_TIMESTAMP);
