-- sunshine-workflow-manager（workflow-manager :8230）
USE sunshine_workflow;

CREATE TABLE workflow_definition (
    tenant_id       VARCHAR(64) NOT NULL DEFAULT 'default',
    id              VARCHAR(64) NOT NULL,
    display_name    VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    mode            VARCHAR(24) NOT NULL DEFAULT 'workflow',
    enabled         TINYINT(1) NOT NULL DEFAULT 0,
    active_version  INT NOT NULL DEFAULT 0,
    source          VARCHAR(16) NOT NULL DEFAULT 'studio',
    maintainer      VARCHAR(64),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id)
);

CREATE TABLE workflow_version (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id       VARCHAR(64) NOT NULL,
    workflow_id     VARCHAR(64) NOT NULL,
    version         INT NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'draft',
    plan_json       MEDIUMTEXT NOT NULL,
    catalog_meta    JSON,
    published_at    TIMESTAMP NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_workflow_version (tenant_id, workflow_id, version),
    CONSTRAINT fk_workflow_version_def FOREIGN KEY (tenant_id, workflow_id)
        REFERENCES workflow_definition (tenant_id, id)
);

-- 标杆 workflow 种子（published v1，plan_json 含 layout；source=seed；节点 id = {type}-{8位hex}）

-- finance-list
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source) VALUES ('default', 'finance-list', '我的报销查询', '列出当前用户报销单（可按 status），不做合规分析', 'workflow', 1, 1, 'seed');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'finance-list', 1, 'published', '{"planId":null,"reason":"导入自 sunshine-workflows.yaml · finance-list","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"tool-f7a3b2c1","type":"tool","displayName":"查询我的报销单","params":{"tool":"sdk__sunshine-finance__list_my_expenses","status":"{{plan.params.status}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据财务工具查询结果回答用户问题。\n\n约束：\n- 仅依据下方「数据」作答；数据中未出现的制度条文、审批标准、金额门槛、住宿/交通/餐补等一律禁止撰写或猜测。\n- 本流程只查询待审批列表：即使用户提到「循环 / 检索制度 / 合规分析」，也只列示数据中的单据；可用一句话说明「当前流程仅列出待审批消息」。\n- 禁止向用户暴露英文流程/工具内部名（如 finance-list、list_my_expenses）。\n- 若「数据」中非空（有条目、条数>0、含 id/金额/标题等），必须逐条列出，不得回答「没有数据」。\n- 仅当数据明确为空数组或条数为 0 时，才可说明当前无待审批记录。\n- 不要编造单据；不要省略工具返回的字段。\n- 输出用简洁 Markdown 列表或表格列单据即可，勿写长篇合规/制度报告。\n\n数据：\n{{tool-f7a3b2c1.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"tool-f7a3b2c1"},{"from":"tool-f7a3b2c1","to":"answer"}],"layout":{"start":{"x":48,"y":72},"tool-f7a3b2c1":{"x":268,"y":72},"answer":{"x":488,"y":72}}}', '{"examples":["有哪些待审批报销","查询待审批的报销和付款消息"],"nodeSummary":["start","tool","answer"]}', CURRENT_TIMESTAMP);

-- finance-smart
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source) VALUES ('default', 'finance-smart', '报销智能分析', '对照制度分析当前用户报销单是否合规（含 Agent 推理）', 'workflow', 1, 1, 'seed');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'finance-smart', 1, 'published', '{"planId":null,"reason":"导入自 sunshine-workflows.yaml · finance-smart","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"tool-d4e8f901","type":"tool","displayName":"查询我的报销单","params":{"tool":"sdk__sunshine-finance__list_my_expenses","status":"{{plan.params.status}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"agent-b2c6d803","type":"agent","displayName":"智能体分析","params":{"query":"{{start.userQuery}}","context":"{{tool-d4e8f901.output}}","skill":"finance-analysis","tools":"sdk__sunshine-finance__list_my_expenses","maxIters":"4","systemOverlay":"本节点仅输出内部分析结论，不面向用户；禁止调用白名单外工具","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据 Agent 分析结果生成用户可见回答。\\n\\n约束：禁止向用户暴露英文流程/工具内部名（如 finance-smart、finance-list）。\\n\\n分析：\\n{{agent-b2c6d803.answer}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"tool-d4e8f901"},{"from":"tool-d4e8f901","to":"agent-b2c6d803"},{"from":"agent-b2c6d803","to":"answer"}],"layout":{"start":{"x":48,"y":72},"tool-d4e8f901":{"x":268,"y":72},"agent-b2c6d803":{"x":488,"y":72},"answer":{"x":708,"y":72}}}', '{"examples":["待审批报销是否合规","对比制度与待办"],"nodeSummary":["start","tool","agent","answer"]}', CURRENT_TIMESTAMP);

-- finance-summary
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source) VALUES ('default', 'finance-summary', '报销汇总统计', '按状态汇总当前用户报销单条数与金额', 'workflow', 1, 1, 'seed');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'finance-summary', 1, 'published', '{"planId":null,"reason":"导入自 sunshine-workflows.yaml · finance-summary","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"tool-a9c1e502","type":"tool","displayName":"汇总我的报销","params":{"tool":"sdk__sunshine-finance__summarize_my_expenses","status":"{{plan.params.status}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据财务汇总工具结果回答用户。\\n\\n约束：禁止向用户暴露英文流程/工具内部名。\\n\\n汇总：\\n{{tool-a9c1e502.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"tool-a9c1e502"},{"from":"tool-a9c1e502","to":"answer"}],"layout":{"start":{"x":48,"y":72},"tool-a9c1e502":{"x":268,"y":72},"answer":{"x":488,"y":72}}}', '{"examples":["待审批有多少条","pending 财务总额"],"nodeSummary":["start","tool","answer"]}', CURRENT_TIMESTAMP);

-- knowledge-qa
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source) VALUES ('default', 'knowledge-qa', '知识库问答', '查企业制度/流程/规定（青松假、网约车上限、安全/IT/法务/行政/PMO 等）；非查个人单据列表或合规对比', 'workflow', 1, 1, 'seed');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'knowledge-qa', 1, 'published', '{"planId":null,"reason":"导入自 sunshine-workflows.yaml · knowledge-qa","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"rag-c5d7e903","type":"rag","displayName":"知识检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"你是企业制度问答助手。仅根据下方「检索结果」回答，不得编造公司制度。\\n\\n若「检索结果」正文为空、或明确写「未找到与用户问题直接相关的片段」，只回复：\\n「企业知识库中暂无相关规定，请咨询 HR/财务或相关主管部门。」\\n若检索结果非空且含与用户问题相关的制度片段（表述可不完全一致，如打车/差旅/交通费/报销），须基于片段作答，不得回复暂无。\\n禁止用通用常识、网络知识或税务/法律科普代替企业制度。\\n禁止向用户输出 finance-list、finance-smart、knowledge-qa 等内部名称；改用中文业务表述。\\n\\n检索结果：\\n{{rag-c5d7e903.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"rag-c5d7e903"},{"from":"rag-c5d7e903","to":"answer"}],"layout":{"start":{"x":48,"y":72},"rag-c5d7e903":{"x":268,"y":72},"answer":{"x":488,"y":72}}}', '{"examples":["青松假有多少天、怎么申请","市内网约车报销上限多少","青松假和网约车报销上限一起查"],"nodeSummary":["start","rag","answer"]}', CURRENT_TIMESTAMP);

-- knowledge-dual（4.7.2 并行双 RAG 标杆）
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source) VALUES ('default', 'knowledge-dual', '双路知识检索', '人事与费用制度并行检索后汇总（如青松假+网约车上限；4.7.2 join 标杆）', 'workflow', 1, 1, 'seed');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'knowledge-dual', 1, 'published', '{"planId":null,"reason":"4.7.2 并行双 RAG 标杆（BPMN parallel-gateway）","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"pg-a1b2c3d4","type":"parallel-gateway","displayName":"并行分叉","params":{"retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"rag-a1b2c3d4","type":"rag","displayName":"制度检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"rag-e5f6a7b8","type":"rag","displayName":"财务检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"join-c9d0e1f2","type":"join","displayName":"并行汇总","params":{"retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"你是企业知识助手。综合下方「制度检索」与「财务检索」结果回答，不得编造。\\n\\n若两路均为空，回复：企业知识库中暂无相关规定。\\n禁止暴露 knowledge-dual 等内部名称。\\n\\n制度检索：\\n{{rag-a1b2c3d4.output}}\\n\\n财务检索：\\n{{rag-e5f6a7b8.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"pg-a1b2c3d4"},{"from":"pg-a1b2c3d4","to":"rag-a1b2c3d4"},{"from":"pg-a1b2c3d4","to":"rag-e5f6a7b8"},{"from":"rag-a1b2c3d4","to":"join-c9d0e1f2"},{"from":"rag-e5f6a7b8","to":"join-c9d0e1f2"},{"from":"join-c9d0e1f2","to":"answer"}],"layout":{"start":{"x":48,"y":72},"pg-a1b2c3d4":{"x":322,"y":80},"rag-a1b2c3d4":{"x":488,"y":28},"rag-e5f6a7b8":{"x":488,"y":116},"join-c9d0e1f2":{"x":762,"y":80},"answer":{"x":928,"y":72}}}', '{"examples":["青松假和网约车报销上限一起查","青松假有多少天、怎么申请"],"nodeSummary":["start","parallel-gateway","rag","join","answer"]}', CURRENT_TIMESTAMP);

-- knowledge-branch（4.13.7 exclusive-gateway 边条件标杆）
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source) VALUES ('default', 'knowledge-branch', '条件分支知识检索', '含「报销」走财务 RAG，否则走人事 RAG（4.13.7 exclusive-gateway 边条件标杆）', 'workflow', 1, 1, 'seed');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'knowledge-branch', 1, 'published', '{"planId":null,"reason":"4.13.7 exclusive-gateway 边条件标杆","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"xg-b1c2d3e4","type":"exclusive-gateway","displayName":"条件分支","params":{"retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"rag-f1a2b3c4","type":"rag","displayName":"财务制度检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"rag-d5e6f7a8","type":"rag","displayName":"人事制度检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"你是企业制度助手。根据下方检索结果回答，不得编造。\\n\\n若检索为空，回复：企业知识库中暂无相关规定。\\n禁止暴露 knowledge-branch 等内部名称。\\n\\n财务制度检索：\\n{{rag-f1a2b3c4.output}}\\n\\n人事制度检索：\\n{{rag-d5e6f7a8.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"xg-b1c2d3e4"},{"from":"xg-b1c2d3e4","to":"rag-f1a2b3c4","condition":{"left":"{{start.userQuery}}","op":"contains","right":"报销"}},{"from":"xg-b1c2d3e4","to":"rag-d5e6f7a8","default":true},{"from":"rag-f1a2b3c4","to":"answer"},{"from":"rag-d5e6f7a8","to":"answer"}],"layout":{"start":{"x":48,"y":72},"xg-b1c2d3e4":{"x":280,"y":80},"rag-f1a2b3c4":{"x":480,"y":28},"rag-d5e6f7a8":{"x":480,"y":116},"answer":{"x":720,"y":72}}}', '{"examples":["网约车报销需要哪些材料","青松假怎么申请"],"nodeSummary":["start","exclusive-gateway","rag","answer"],"intentAfter":"将按条件分支知识检索流程处理"}', CURRENT_TIMESTAMP);
-- knowledge-loop（4.13.7 do-while 继续条件；框内 rag→tool→agent 标杆）
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source) VALUES ('default', 'knowledge-loop', '条件循环知识检索', 'do-while：首轮必进框内 rag→tool→agent；含「继续」则再轮（最多 2，超限 exit）（4.13.7）', 'workflow', 1, 1, 'seed');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'knowledge-loop', 1, 'published', '{"planId":null,"reason":"4.13.7 loop 容器标杆（do-while 继续条件 contains「继续」；框内 rag→tool→agent）","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"loop-a1b2c3d4","type":"loop","displayName":"条件循环","params":{"condition.left":"{{start.userQuery}}","condition.op":"contains","condition.right":"继续","maxIterations":"2","onMaxIterations":"exit","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"fail_fast"}},{"id":"rag-l1o2o3p4","type":"rag","parentId":"loop-a1b2c3d4","displayName":"知识检索","params":{"query":"{{start.userQuery}}","topK":"3","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"tool-t1o2o3p4","type":"tool","parentId":"loop-a1b2c3d4","displayName":"查询我的待报销","params":{"tool":"sdk__sunshine-finance__list_my_expenses","status":"{{plan.params.status}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"agent-a1g2e3n4","type":"agent","parentId":"loop-a1b2c3d4","displayName":"综合分析","params":{"query":"{{start.userQuery}}","context":"检索：{{rag-l1o2o3p4.output}}\\\\n待办：{{tool-t1o2o3p4.output}}","skill":"finance-analysis","tools":"sdk__sunshine-finance__list_my_expenses","maxIters":"3","systemOverlay":"本节点仅输出内部分析结论；综合制度检索与待办数据，禁止编造。","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"你是企业助手。根据下方循环分析结论回答，不得编造。\\\\n\\\\n若结论为空，回复：暂无可用结果。\\\\n禁止暴露 knowledge-loop 等内部名称。\\\\n\\\\n循环分析：\\\\n{{loop-a1b2c3d4.output}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"loop-a1b2c3d4"},{"from":"rag-l1o2o3p4","to":"tool-t1o2o3p4"},{"from":"tool-t1o2o3p4","to":"agent-a1g2e3n4"},{"from":"loop-a1b2c3d4","to":"answer"}],"layout":{"start":{"x":48,"y":72},"loop-a1b2c3d4":{"x":200,"y":40,"width":560,"height":160},"rag-l1o2o3p4":{"x":224,"y":92},"tool-t1o2o3p4":{"x":412,"y":92},"agent-a1g2e3n4":{"x":600,"y":92},"answer":{"x":820,"y":72}}}', '{"examples":["分析青松假余额和我的待报销","继续分析青松假余额和我的待报销"],"nodeSummary":["start","loop","rag","tool","agent","answer"],"intentAfter":"将按条件循环（检索→工具→智能体）流程处理"}', CURRENT_TIMESTAMP);

-- sandbox-agent（4.5 SUB 默认沙箱标杆：agent 节点写 /workspace）
INSERT INTO workflow_definition (tenant_id, id, display_name, description, mode, enabled, active_version, source) VALUES ('default', 'sandbox-agent', '沙箱子 Agent 写文件', 'Workflow agent 节点默认沙箱：用 sandbox__* 在对话工作区写文件后汇总（4.5 SUB 默认沙箱标杆）', 'workflow', 1, 1, 'seed');
INSERT INTO workflow_version (tenant_id, workflow_id, version, status, plan_json, catalog_meta, published_at) VALUES ('default', 'sandbox-agent', 1, 'published', '{"planId":null,"reason":"4.5 SUB 默认沙箱标杆（start→agent→answer；复用对话级 /workspace）","nodes":[{"id":"start","type":"start","displayName":"开始","params":{}},{"id":"agent-s4b0x7a1","type":"agent","displayName":"沙箱写文件","params":{"query":"{{start.userQuery}}","context":"请在对话沙箱 /workspace 完成用户请求的文件写入；沙箱六工具已注入，无需 Catalog 白名单。","maxIters":"4","systemOverlay":"本节点为 Workflow 子 Agent，仅输出内部结论供下游润色。\\n必须使用 sandbox__write（新建）或 sandbox__edit（已存在）在 /workspace 落盘；过渡语后立刻 tool call。\\n禁止编造「已写入」而未实际调用工具；完成后用简短中文说明路径与要点。","retry.maxAttempts":"1","retry.backoffMs":"500","retry.onFailure":"continue"}},{"id":"answer","type":"answer","displayName":"回答","params":{"prompt":"根据子 Agent 结论生成用户可见回答。\\n\\n约束：禁止暴露 sandbox-agent、sandbox__* 等内部名；用中文说明已写入的工作区文件路径与内容要点。\\n\\n子 Agent 结论：\\n{{agent-s4b0x7a1.answer}}","retry.maxAttempts":"2","retry.backoffMs":"500","retry.onFailure":"fail_fast"}}],"edges":[{"from":"start","to":"agent-s4b0x7a1"},{"from":"agent-s4b0x7a1","to":"answer"}],"layout":{"start":{"x":48,"y":72},"agent-s4b0x7a1":{"x":268,"y":72},"answer":{"x":488,"y":72}}}', '{"examples":["在工作区写一份 hello.txt 内容为 hello sandbox","用沙箱新建 /workspace/note.md"],"nodeSummary":["start","agent","answer"],"intentAfter":"将按沙箱子 Agent 写文件流程处理"}', CURRENT_TIMESTAMP);
